# Change these first
owner: SamPetherbridge # Your GitHub username
repo: status.httpstatus.xyz # Your GitHub repository name

# Add your sites here
sites:
  - name: 200 Ok - GET
    url: https://httpstatus.xyz/200
    method: GET
    expectedStatusCodes:
      - 200
  - name: 200 Ok - POST
    url: https://httpstatus.xyz/200
    method: POST
    expectedStatusCodes:
      - 200


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.httpstatus.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HTTPStatus.xyz - Status
  introTitle: "HTTPStatus.xyz Status"
  introMessage: "Status page for HTTPStatus.xyz powered by GitHub."
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */1 * * *"
